spring:
  application:
    name: photoroster
  profiles:
    active: redis-session
  session:
    store-type: none
#  output:
#    ansi:
#      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
photoroster:
  version: @app.version@
  env: ${app.env}
  roleGroupings: TeacherEnrollment,StudentEnrollment,ObserverEnrollment,TaEnrollment,DesignerEnrollment,OtherEnrollment

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m

---

spring:
  profiles: redis-session
  session:
    store-type: redis
    redis.namespace: photoroster-${app.version}:session